### ISSUE TITLE
UTF-8 character encoding

### ISSUE THREAD

**Issue by jonjamcam** [BHSPitMonkey/ninjam-js#6]
Hello. I came across Ninjam JS some days ago and I find it a very interesting project.

 Currently I'm collaborating with Jamtaba2 ninjam client (https://github.com/elieserdejesus/JamTaba) and we are trying to find a solution to some encoding problems related to the Chat messages when different clients are communicating (see https://github.com/elieserdejesus/JamTaba/issues/441 for more info)

The problem seems to be solved for the clients that uses UTF-8 encoding. I did some tests using NINJAM JS (https://github.com/elieserdejesus/JamTaba/issues/441#issuecomment-227650813), but the result was not good.

 Is it possible that you could adopt the UTF-8 standard so non-english users can chat in their native languages cross-platform?

Cheers.

Jon

**Comment by BHSPitMonkey** [comment]
Yep, this has been on my TODO list but I haven't found the time to dig into it yet. Thanks for testing and opening an issue.

**Comment by BHSPitMonkey** [comment]
Landed in [v0.4.4](https://github.com/BHSPitMonkey/ninjam-js/releases/tag/v0.4.4) (7d0f102).

**Comment by jonjamcam** [comment]
Thank YOu! It's communicating OK now:

![image](https://cloud.githubusercontent.com/assets/15310433/16304651/c05a1050-392c-11e6-89bd-819f72cf4e4a.png)
